### ISSUE TITLE
Modifying the relation field causes a race condition

### ISSUE THREAD

**Issue by mquandalle** [lfades/cottz-publish#4]
Due to a bug in publish-composite (https://github.com/englue/meteor-publish-composite/issues/29#issuecomment-69937916) I've been considering using this package as an alternative. However it appears to have a similar problem.

@Goluis Could you please take a look at the issue linked above?

**Comment by Goluis** [comment]
I'm using this package to run publications with up to 5 collections together without any problem (using Kadira).
but really can not say that this is not happening, I'll run some tests as soon as possible.

**Comment by mquandalle** [comment]
Thank you for your answer. I was calling `this.cursor` twice in the same function which you mark as a limitation in the README. So it's maybe a false alarm, and not the same problem I experienced with publish-composite.

I'll test again and share any result.

**Comment by Goluis** [comment]
the limitation is when you try to post a cursor with the same name collection 2 times not when you use
`this.cursor` several times, I guess my readme is not very clear with that

**Comment by mquandalle** [comment]
Ok so it was a mistake with my testing methodology, it seems to work, at least it doesn't have the same issue as publish-composite. Sorry for the false alarm.

But I have another issue, I sometimes experience data loss (depublication). I'll investigate this issue tomorrow but if you just want to have a quick look you can go to http://libreboard.com, create a board and add ~30 cards in the first column. Then use the column menu to “move all cards in this list” into the second column. Repeat the operation a few times and you should experience data depublication. Reloading the page solves the issue. Did you already experience something similar?

**Comment by Goluis** [comment]
you're right, the information is lost, at this time I am reviewing the package and if not find the solution I will review libreboard also on github

**Comment by Goluis** [comment]
I have found the error, I will implement the solution

**Comment by mquandalle** [comment]
Oh great, thank you!

**Comment by mquandalle** [comment]
Did you get a chance to work on this? Feel free to share what the problem is if I can help implement a solution.

**Comment by Goluis** [comment]
when a card is updated two messages are received in the observer: removed and added. removed goes first and then added adds again the document.

but when all 30 cards are updated at the same time these messages are confused and added arrive first and then are deleted

in publish-composite messages are also confused but keep coming Added first.
right now I have a version of cottz-publish that I did to fix this problem but not 100% guaranteed because I still have not finished
